### PR TITLE
Light FX

### PR DESCRIPTION
**Pull request by SuicidalInsanity**
-Add Light FX toggle for performance/parallax compatibility
-Rejigger Graphics/UI section slightly, stick performant options under new Enable FX toggle (Gapless Smoke/Flare FX/Water hits/Light FX)

### CODE REVIEW

**Review by BrettRyland — COMMENTED** [review]
I'm still seeing planes lit up from bullet hit explosions when LightFX is disabled, so I'm not sure if it's working correctly.

**Comment by SuicidalInsanity** [comment]
It's possible the stock BDA explosions (or at least the 30mmExplosion most of the guns use) have intrinsic Light components that come with the model which wouldn't be getting caught, since gameObject.GetComponent<T>() simply returns the first component T it finds, testing...

**Comment by BrettRyland** [comment]
> Which guns were you using? It's possible the stock BDA explosions (or at least the 30mmExplosion most of the guns use) have intrinsic Light components that come with the model which wouldn't be getting caught, since gameObject.GetComponent< T>() simply returns the first component T it finds; testing...

It was with my usual mix of planes, which mostly use just the hidden vulcan and the browning, so it'd be the stock BDA explosions doing it. I'll test the latest changes tonight.

**Comment by SuicidalInsanity** [comment]
Teach me to refresh the page first...
We good to merge this and get a release out?

**Pull request merged**
