### PR TITLE
Accuracy tuning

### PR DESCRIPTION
**Pull request by SuicidalInsanity**
Adds player-modifiable accuracy tuning to the AutoFireCosAngle firing tolerance check

### CODE REVIEW

**Comment by BrettRyland** [comment]
`weapon.Current.maxAutoFireCosAngle = vessel.LandedOrSplashed ? adjustedAutoFireCosAngle : 0.9993906f; //user-adjustable from 0-2deg` means that it only uses the `adjustedAutoFireCosAngle` value if the vessel is landed or splashed. If it's airborne then it's using the fixed value of 2°.

I think that if the user can specify the angle, then you can remove the `vessel.LandedOrSplashed` check and just have `weapon.Current.maxAutoFireCosAngle = adjustedAutoFireCosAngle`

Also, for the `if (LastAFCAA != AutoFireCosAngleAdjustment)`, I think you can use an event handler to trigger this instead of checking it every update. Have a look at `OnMinUpdated` in BDModulePilotAI.cs.

**Comment by SuicidalInsanity** [comment]
The UI_FloatRange.OnFieldChanged event handler only calls when the FloatRange slider is being modified by the player adjusting the slider; it will not recognize the float being externally modified by the WM GUI slider.

**Comment by BrettRyland** [comment]
> Will need a chinese loc update as well

Absolutely. The rest of the additions that have been made since I started working on BDA haven't had Chinese LOC added since I don't know Chinese. If you have any contact with someone willing to do the translation, that'd be quite useful!

**Comment by BrettRyland** [comment]
> The UI_FloatRange.OnFieldChanged event handler only calls when the FloatRange slider is being modified by the player adjusting the slider; it will not recognize the float being externally modified by the WM GUI slider.

That's easy enough to handle by directly calling the event callback. E.g.,
```
diff --git a/BDArmory/Modules/MissileFire.cs b/BDArmory/Modules/MissileFire.cs
index e2d320d9..5b91e20d 100644
--- a/BDArmory/Modules/MissileFire.cs
+++ b/BDArmory/Modules/MissileFire.cs
@@ -864,7 +864,7 @@ public void Start()
                 GameEvents.onPartDie.Add(OnPartDie);
 
                 GetTotalHP();
-                StartCoroutine(SetAFCAA());
+                // StartCoroutine(SetAFCAA());
 
                 using (List<IBDAIControl>.Enumerator aipilot = vessel.FindPartModulesImplementing<IBDAIControl>().GetEnumerator())
                     while (aipilot.MoveNext())
@@ -876,6 +876,8 @@ public void Start()
 
                 RefreshModules();
             }
+
+            ((UI_FloatRange)Fields["AutoFireCosAngleAdjustment"].uiControlEditor).onFieldChanged = SetAFCAA_;
         }
 
         void OnPartDie()
@@ -1783,10 +1785,17 @@ private IEnumerator SetAFCAA()
             WaitForSeconds wait = new WaitForSeconds(2); //cache this to prevent mem allocation every call from yield return new waitforseconds (n)
             while (enabled)
             {
-                adjustedAutoFireCosAngle = Mathf.Cos((AutoFireCosAngleAdjustment * Mathf.Deg2Rad)); //mathf.Cos outputs to rad, apparently? mathf.Cos = -0.416, not 0.9993
+                adjustedAutoFireCosAngle = Mathf.Cos((AutoFireCosAngleAdjustment * Mathf.Deg2Rad));
+                Debug.Log("DEBUG AFCAA adjusted to " + AutoFireCosAngleAdjustment + ": " + adjustedAutoFireCosAngle);
                 yield return wait;
             }
         }
+
+        public void SetAFCAA_(BaseField field, object obj)
+        {
+            adjustedAutoFireCosAngle = Mathf.Cos((AutoFireCosAngleAdjustment * Mathf.Deg2Rad));
+            Debug.Log("DEBUG AFCAA adjusted to " + AutoFireCosAngleAdjustment + ": " + adjustedAutoFireCosAngle);
+        }
         #endregion Enumerators
 
         #region Audio
diff --git a/BDArmory/UI/BDArmorySetup.cs b/BDArmory/UI/BDArmorySetup.cs
index 34e67fbf..eb6a176f 100644
--- a/BDArmory/UI/BDArmorySetup.cs
+++ b/BDArmory/UI/BDArmorySetup.cs
@@ -967,7 +967,8 @@ void WindowBDAToolbar(int windowID)
                         GUI.HorizontalSlider(
                             new Rect(leftIndent + (90), (guardLines * entryHeight), contentWidth - 90 - 38, entryHeight),
                             ActiveWeaponManager.AutoFireCosAngleAdjustment, 0, 2);
-                    ActiveWeaponManager.AutoFireCosAngleAdjustment = Mathf.Round(ActiveWeaponManager.AutoFireCosAngleAdjustment * 100) / 100;
+                    if (ActiveWeaponManager.AutoFireCosAngleAdjustment != (ActiveWeaponManager.AutoFireCosAngleAdjustment = Mathf.Round(ActiveWeaponManager.AutoFireCosAngleAdjustment * 100) / 100))
+                        ActiveWeaponManager.SetAFCAA_(null, null);
                     GUI.Label(new Rect(leftIndent + (contentWidth - 35), (guardLines * entryHeight), 35, entryHeight),
                         ActiveWeaponManager.AutoFireCosAngleAdjustment.ToString(), leftLabel);
                     guardLines++;

```

**Pull request merged**
